"""create profile_pic table

Revision ID: 502077650ff7
Revises: 69ca5847c0a3
Create Date: 2019-02-27 11:38:28.546723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502077650ff7'
down_revision = '69ca5847c0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_photos')
    # ### end Alembic commands ###
